Dockerfile
sls_api/endpoints/facsimiles.py
sls_api/endpoints/generics.py

Ideally, these files would be in TIFF format for optimal image conversion, but accept png and jpg as well for usability.

Add endpoint for uploading facsimile files

---

sls_api/endpoints/text.py

If the language of an established text or a manuscript is defined in the database, include the language value in the endpoint response. This is needed for the frontend to correctly add lang-attributes to the HTML in case the texts are in a different language than the user interface.
This commit also removes
```
if language is not None:
data["language"] = language
```
from the est endpoint because there is no need to include the request language in the response.

Add language from database to est and ms text endpoint responses

---

sls_api/endpoints/metadata.py

This update modifies the endpoints for getting all publication collections as well as a specific collection with a language parameter, so the names of the collections can be fetched in a specific language:
```
@meta.route("/<project>/collections")
@meta.route("/<project>/collections/<language>")
```
```
@meta.route("/<project>/collection/<collection_id>")
@meta.route("/<project>/collection/<collection_id>/i18n/<language>")
```
The new frontend already supports these endpoints, and, for instance, they are required for the English and Arabic versions of granqvist.sls.fi to work with the new frontend.
**Required database modification:** This update requires that a column named `name_translation_id` is added to the `publication_collection` table in the digital edition database. It should be …

feature: support multilingual collections

---

sls_api/configs/digital_editions_example.yml
sls_api/endpoints/generics.py
sls_api/endpoints/media.py

Three changes:
1. Dynamically set the Access-Control-Allow-Origin header to the request origin if the origin is a *.sls.fi subdomain. This makes it possible to embed PDFs served by the API on these sites. For example, In the new frontend of granqvist.sls.fi PDF books are embedded in the web page. Currently the browser blocks these PDFs from being displayed embedded because of the lack of a Access-Control-Allow-Origin header in the response from api.sls.fi.
This is just a suggested fix, there might be a better solution. Currently the main domain "sls.fi" is hard-coded as an allowed origin, but it would be better if the allowed domain(s) would be read from the config.
3. Refactor if-elif code block setting `file_path` so there is only one branch per file type, and explicitly add mimetype to …

fix: set CORS header for `get_pdf_file` endpoint

---

sls_api/endpoints/metadata.py

There was errors in the previous SQL query, it tried to fetch a field (`alternative_form`) which is not present in the `subject` table.
I think this is because the i18n version of the endpoint was originally created by Toffe Björkskog for the Mechelin project, and they have a slightly different table structure than SLS.

fix i18n version of get subjects endpoint

---

sls_api/endpoints/tools/collections.py

The `name_translation_id` field was recently added to the `publication_collection` table. This pull request adds the field to the return value of the tools endpoint for listing all publication collections in a project.

Add missing field to tools endpoint returning list of publication collections

---

sls_api/endpoints/tools/events.py

Add new translation:
- `neutral_text` can be passed as POST data.
- `parent_translation_field` can be passed as POST data for cases when the field holding translation_id has a different name (applies to some tables).
- Changed default value for `language` to None.
- Improved documentation.
Edit translation:
- An existing translation can be updated simply by passing the id of the translation in the `translation_text` table (`translation_text_id` key).
- Only fields in the POST data are updated, previously fields missing from the POST data would be set to None.
- Added the possibility to update the `deleted` field of a translation.
- Improved documentation.

Fix tools-endpoints for adding new and editing translations

---

sls_api/endpoints/tools/collections.py
sls_api/endpoints/tools/publishing.py

- The `language` field was added to the `publication` table a while ago.
- The edit_publication endpoint now supports updating all fields of a publication.

fix missing fields in new_publication and edit_publication endpoints

---

sls_api/endpoints/generics.py
sls_api/endpoints/tools/collections.py
sls_api/endpoints/tools/events.py
sls_api/endpoints/tools/publications.py
sls_api/endpoints/tools/publishing.py
sls_api/exceptions.py

This PR contains fixes to and refactoring of multiple tools-endpoints, mainly related to project, publication collection, publication comment/manuscript/version management.
The changes involve:
- Modifying which fields are editable and aligning the field names in POST data with the field names in the database.
- Using SQLAlchemy’s context manager to automatically handle commits and rollbacks.
- Using SQLAlchemy’s Core methods.
- Adding field and field value validation.
- Endpoints performing INSERT and UPDATE operations include the affected row(s) in the response.
- Standardising JSON responses for the tools-endpoints (see below).
- Adding a new endpoint (`list_user_projects` in `publishing.py`) for listing all projects the current user has access to.
- Adding a new endpoint …

refactor and fix tools-endpoints

---

sls_api/endpoints/tools/collections.py
sls_api/endpoints/tools/events.py
sls_api/endpoints/tools/publications.py
sls_api/endpoints/tools/publishing.py

When using `exception()` to log errors the exception message and stack trace are automatically included.

tools: remove redundant exception message in logger.exception calls

---

sls_api/endpoints/tools/collections.py

- Use SQLAlchemy Core methods instead of raw SQL.
- Add URL path parameters for ordering the result.

tools: refactor list publication collection endpoint

---

sls_api/endpoints/tools/files.py

- Standardize response format.
- Validate `file_path`.
- Remove running `git fetch` as it does not have any bearing on the result.
- Add exception logging.

tools: refactor `get_file_tree` endpoint

---

sls_api/endpoints/tools/files.py

The endpoint returns the projects git repository name and current branch. This can be useful to display in the CMS frontend.

tools: add endpoint to get project git repo details

---

sls_api/configs/digital_editions_example.yml
sls_api/endpoints/generics.py
sls_api/endpoints/tools/files.py

This adds an endpoint that can be used to retrieve metadata from an XML file defined in the path provided as a URL path parameter.
This simplifies adding publications (and manuscripts and versions) to the database, when some of the required data (like text title and date of origin) for the database can be read from the XML file of the publication, and doesn't have to be manually inserted.
The code uses the Python ElementTree XML API for parsing.

tools: add endpoint for getting publication metadata from xml

---

.gitignore
sls_api/endpoints/tools/files.py

Modifies the tools-endpoint for extracting metadata from TEI XML documents in two ways:
1. "genre" now supported.
2. "original_publication_date" can be extracted from a separate element for correspondence. Also fixes validation of the date, which wasn't always applied previously.

tools: extract "genre" metadata from TEI XML and improve "date" extraction

---

setup.py
sls_api/scripts/publisher.py
sls_api/scripts/saxon_xml_document.py

The current publisher script generates web XML files according to a process that was defined for Zacharias Topelius Skrifter (ZTS) over 10 years ago. It requires the source TEI XML files to be encoded using the same principles as ZTS. However, the TEI guidelines have evolved, ZTS was never fully TEI-compliant, and SLS now has new, TEI-compliant guidelines on how texts should be encoded.
This update adds a new processing mode to the publisher script. When this mode is activated, the web XML files are generated from the source files using XSLT which resides in the project files. This brings flexibility, as the XSLT can be modified for each project, if needed, and the source XML files don't necessarily even have to be in TEI XML. XSLT processing of the source files is enabled by utilising …

publisher: add XSLT processing option

---

sls_api/endpoints/tools/files.py

Slight refinements to the XPath expressions used to extract metadata from XML. Switched to `lxml.etree` to be able to use the `xpath()` method which has full XPath 1.0 support.

tools: refine metadata extraction from XML

---

sls_api/endpoints/generics.py
sls_api/endpoints/text.py

Currently, string parameters passed to the XSLT processors are manually wrapped in double quotes (`""`) to escape any single quotes (`'`) in the value. This is done because `lxml` treats string parameters as literal XPath expressions.
However, this approach does not handle strings that contain double quotes themselves, potentially leading to invalid or broken XPath expressions.
`lxml` provides a built-in function, `etree.XSLT.strparam()`, which safely escapes all necessary characters in string parameters. Additionally, the `Saxon` processor does not require any quoting or escaping, as parameters are passed as typed XDM values.
This PR:
- Centralizes the quoting/escaping logic for string parameters in `transform_xml()` (inside `generics.py`).
- Applies quoting only when using the lxml …

Fix escaping of XSLT string parameters

---

sls_api/endpoints/generics.py
sls_api/endpoints/metadata.py
sls_api/endpoints/tools/files.py

This PR creates two separate endpoints for handling collection table of contents:
- In the Tools API (tools/files.py), which requires authentication, the endpoint enables GET and PUT of collection table of contents.
- In the public API (metadata.py), which is used by the edition frontends and doesn't require authentication, the endpoint enables GET of collection table of contents.
Having two separate endpoints instead of one (like before) is motivated because a) it's clearer to not mix non-public endpoints with public ones and to have all the Tools endpoints in a separate set of files; b) the GET responses of the two endpoints differ in format:
- In the tools API the endpoint responds in the standardized way for the frontend CMS.
- In the public API the endpoint responds with the table of …

Refactor collection ToC handling

---

sls_api/endpoints/tools/files.py

Adds a new endpoint, which can be used to update the names and dates of publications in a collection table of contents with the latest data in the database.
The endpoint responds with the updated ToC, but does not save it on the server. The idea is that the frontend can use the endpoint to get the updated ToC, then the frontend user can review the changes before saving them.

Tools: add endpoint to get ToC updated with publication data from database

---

sls_api/endpoints/generics.py
sls_api/endpoints/metadata.py
sls_api/endpoints/tools/events.py
sls_api/endpoints/tools/publications.py

This commit modifies the tools-endpoints for managing tags and events in the database. Endpoints that are modified or added enable:
- listing project tags
- adding new tags to a project
- editing existing tags
- listing tags connected to a publication
- adding new events
- deleting existing events
Event-related tools-endpoints that are not used have been removed.

Tools: refactor tags endpoints
